sudo: required

services:
  - docker

language: python
python:
  - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
- docker pull diblab/eel-pond

# command to run tests
script:
- docker run diblab/eel-pond /bin/sh -c "ls /root"
