sudo: required

services:
  - docker

language: python
python:
  - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
- docker pull diblab/eel-pond:0.1
- curl -O https://s3.amazonaws.com/public.ged.msu.edu/mrnaseq-subset.tar
- mkdir data
- cd data && tar xf ../mrnaseq-subset.tar

# command to run tests
script:
- docker run -v $(pwd):/mnt diblab/eel-pond:0.1 /bin/sh -c "ls /mnt"
