sudo: required

services:
  - docker

language: python
python:
  - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
- docker pull ubuntu:15.10
- docker run ubuntu:15.10 /bin/sh -c "echo hello, world"


# command to run tests
script: py.test
