sudo: required

services:
  - docker

language: python
python:
  - "3.5"

before_install:
- docker pull diblab/eel-pond:0.1

# command to install dependencies
install:
- "pip install -r requirements.txt"
- curl -O https://s3.amazonaws.com/public.ged.msu.edu/mrnaseq-subset.tar
- mkdir data
- cd data && tar xf ../mrnaseq-subset.tar; cd ..

# command to run tests
script:
- docker run --name longy -v $(pwd):/mnt diblab/eel-pond:0.1 /bin/sh -c "ls -R /mnt"
- docker run longy /bin/sh -c "/mnt/update-software.sh"
#- docker run -v $(pwd):/mnt diblab/eel-pond:0.1 /bin/sh -c "PROJECT=/mnt /mnt/1-quality.rst.sh"
#- docker run -v $(pwd):/mnt diblab/eel-pond:0.1 /bin/sh -c "PROJECT=/mnt /mnt/2-diginorm.rst.sh"
#- docker run -v $(pwd):/mnt diblab/eel-pond:0.1 /bin/sh -c "PROJECT=/mnt /mnt/3-big-assembly.rst.sh"
